aula/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from blog.views import login_view, logout_view

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^admin/', admin.site.urls),
	url(r'^login/$', login_view, name='login'),
	url(r'^logout/$', logout_view, name='logout'),
	url(r'^post/', include('blog.urls', namespace='blog')),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^create/$', views.create_post, name='create'),
	url(r'^list/$', views.list_posts, name='list'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.edit_post, name='edit'),
	url(r'^detail/(?P<pk>[0-9]+)/$', views.detail_post, name='detail'),
	url(r'^remove/(?P<pk>[0-9]+)/$', views.remove_post, name='remove'),

]

blog/models.py
# encoding: utf-8
from __future__ import unicode_literals

from django.db import models

class Post(models.Model):
	texto = models.TextField()
	titulo = models.CharField(max_length=150)
	autor = models.ForeignKey('auth.User')
	data_criacao = models.DateTimeField(auto_now_add=True, editable=False)
	data_edicao = models.DateTimeField(auto_now=True, editable=False)
	like = models.IntegerField()

	def __str__(self):
		return self.titulo


class Comentario(models.Model):
	texto = models.TextField()
	post = models.ForeignKey(Post, related_name='comentarios', on_delete=models.CASCADE)
	like = models.BooleanField()
	autor = models.ForeignKey('auth.User')
	data = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.texto

blog/forms.py
# encoding: utf-8
from django import forms
from django.contrib.auth import authenticate
from .models import Post, Comentario


class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('titulo', 'texto')


class ComentarioForm(forms.ModelForm):

	class Meta:
		model = Comentario
		fields = ('texto', 'like')


class LoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput)

	def clean(self):
		super(LoginForm, self).clean()
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		if not user:
			raise forms.ValidationError(u'Login ou senha inválidos')
		return self.cleaned_data

aula/views.py
from django.shortcuts import render
from blog import models

def index(request):
	objects = models.Post.objects.all().order_by('-data_edicao')
	return render(request, 'base.html', {'objects' : objects})

blog/views.py
from .forms import *
from .models import Post
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404

@login_required
# Decorator para restringir apenas para usuários logados
# Mais sobre Decorators: http://wiki.python.org.br/Decoradores_Python_(Pyt)m)ncihon_Decorators)
def create_post(request):
# Função para a página de criação de Posts, recebe a requisição como parametro
    if request.method == 'POST': # Caso a requisição seja do tipo POST (envio de formulário) precisamos processar o formulário
	form = PostForm(request.POST) # Instanciamos o formulário passando a requisição
	if form.is_valid(): # Verificamos se o formulário é válido conforme as validações da classe
	    post = form.save(commit=False) # Criamos uma instancia de Post, mas ainda não salvamos no banco de dados
	    post.autor = request.user # Definimos o usuário logado atualmente como autor do Post
	    post.like = 0 # Definimos o número de likes como 0 (gambiarras)
	    try:
		post.save() # Salvamos o Post no banco de dados
		return redirect(reverse('blog:list')) # Redirecionamos para a lista de Posts
	    except Exception as e:
		print(e)
    else:
        # Caso a requisição não seja do tipo POST, quer dizer que estamos só acessando a página
        form = PostForm() # Portanto instanciamos um formulário vazio a ser mostrado na página
    return render(request, 'create_post.html', {'form': form}) # Retornamos a página HTML injetando o formulário vazio

@login_required
def list_posts(request):
# Função para a página de listagem de Posts
    posts = Post.objects.all()
    # Recuperamos todos os Posts do banco de dados através da ORM do Django
    # Mais sobre ORM: http://turing.com.br/material/acpython/mod3/django/orm1.html
    return render(request, 'posts.html', {'posts': posts}) # Retornamos a página HTML injetando os Posts

def detail_post(request, pk):
# Função para a página de detalhes de um Post, recebe a requisição e uma chave como parametros
    # Procura pelo Post escolhido através da chave ou devolve um erro HTTP 404 caso não encontre
    # Mais sobre HTTP 404: https://pt.wikipedia.org/wiki/HTTP_404
    post = get_object_or_404(Post, pk=pk)
    # Novamente temos um formulário, portanto quando a requisição for de envio de dados precisamos processa-lo
    if request.method == 'POST':
	form = ComentarioForm(request.POST) # Instanciamos um formulário com a requisição
	comentario = form.save(commit=False) # Instanciamos um Comentário, mas ainda não salvamos no banco de dados
	comentario.autor = request.user # Definimos como autor do Comentário o usuário logado
	comentario.post = post # Definimos como Post do comentário o Post que está sendo visualizado
	comentario.save() # Salvamos o comentário no banco de dados
    form = ComentarioForm() # Caso a requisição não seja de envio de dados, novamente criamos um formulário vazio
    # Retornamos a página HTML injetando o Post que foi buscado no banco de dados, e o formulário de comentários
    return render(request, 'post.html', {'post': post, 'form': form})

@login_required
def edit_post(request, pk):
# Função para a página de edição de Posts, recebendo a requisição e uma chave como parametros
    # Novamente, procura pelo Post através da chave passada ou retorna um erro HTTP 404
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        # Novamente temos que processar um formulário, mas dessa vez declaramos que a instancia é o Post buscado do banco
	form = PostForm(request.POST, instance=post)
	if form.is_valid():
	    form.save()
	    return redirect(reverse('blog:list'))
    else:
        # Caso não estejamos processando um formulário, não passamos a requisição como parametro
        # Mas passamos a instancia ainda sim, porque estaremos mostrando o formulário com os dados de um Post já cadastrado
	form = PostForm(instance=post)
    return render(request, 'create_post.html', {'form': form})

@login_required
def remove_post(request, pk):
# Função para a página de exclusão de um Post através da chave passada por parametro
    post = get_object_or_404(Post, pk=pk)
    post.delete() # Exclui do banco de dados o Post
    return redirect(reverse('blog:list'))

def login_view(request):
# Função para a página de login
    if not request.user.is_anonymous: # Verifica se o usuário já não está logado no sistema
	return redirect(reverse('index')) # Caso já esteja, redirecionamos imediatamente para a página inicial
    if request.method == 'POST':
	form = LoginForm(request.POST) # Novamente, processamos um formulário com a requisição
	if form.is_valid():
	    username = request.POST.get('username') # Recuperamos o username enviado no formulário
	    password = request.POST.get('password') # Recuperamos a senha enviada no formulário
            # Procuramos por um usuário no banco de dados que tenha este nome e esta senha
	    user = authenticate(username=username, password=password)
	    if user: # Caso encontremos um usuário com o usuário e a senha no banco
		login(request, user) # Autenticamos este usuário
		return redirect(reverse('blog:list')) # Redirecionamos para a lista de Posts
    else: # Caso a requisição seja simplesmente um acesso à página (GET)
	form = LoginForm() # Criamos um formulário vazio
    return render(request, 'login.html', {'form': form}) # Retornamos a página HTML injetando o formulário

@login_required
def logout_view(request):
# Função para logout, auto-explicativa
    logout(request)
    return redirect(reverse('index'))

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}">
		<script src="{% static 'lib/jquery.min.js' %}"></script>
		<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
		<meta charset="utf-8">
	</head>
	<body>
	{% block menu %}
		<nav class="navbar navbar-default">
		 	<div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					  <ul class="nav navbar-nav">
					{% if request.user.is_authenticated %}
						<li class="dropdown">
						  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Post <span class="caret"></span></a>
						  <ul class="dropdown-menu">
							<li><a href="{% url 'blog:list' %}">Listar</a></li>
							<li><a href="{% url 'blog:create' %}">Inserir</a></li>
						  </ul>
						</li>
						<li>
							<a href="{% url 'logout' %}">Logout</a>
						</li>
						{% else %}
						<li>
							<a href="{% url 'login' %}">Login</a>
						</li>
						{% endif %}
					  </ul>
				</div>
			</div>
		</nav>
		{% endblock menu %}
		<div class="container">
			<div class="col-md-12">
				{% block content %}
					{% for obj in objects %}
						<div class="panel panel-default">
						  <div class="panel-heading"><a href="{% url 'blog:detail' obj.id %}">{{ obj.titulo }} escrito por {{ obj.autor }}</a></div>
						  <div class="panel-body">
							    {{ obj.texto }}
						  </div>
						</div>
					{% endfor  %}
				{% endblock content %}
			</div>
		</div>
	</body>
</html>

blog/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-default">Salvar</button>
	</form>
{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}
{% block menu %}
{% endblock menu %}
{% block content %}
<div class="col-md-4 col-md-offset-4">
	<h2>Login</h2>
	<form method="POST">
		{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-default">Login</button>
	</form>
</div>
{% endblock %}

blog/templates/post.html
{% extends 'base.html' %}
{% block content %}
	<h1>{{ post.titulo }}</h1>
	<p>{{ post.texto }}</p>
	<h2>Comentários</h2>
	<ul>
	{% for comentario in post.comentarios.all %}
		<li>{{ comentario.texto }}</li>
	{% endfor %}
	</ul>
	{% if request.user.is_authenticated %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Enviar</button>
	</form>
	{% endif %}
{% endblock %}

blog/templates/posts.html
{% extends 'base.html' %}
{% block content %}
	<h2>Post - Listagem</h2>
	<div class="text-right">
		<a class="btn btn-default" role="button"  href="{% url 'blog:create' %}">
			<i class="glyphicon glyphicon-plus"></i> Cadastrar novo
		</a>
	</div>
	<table class="table">
		<thead>
			<th>Titulo</th>
			<th>Texto</th>
			<th></th>
		</thead>
		<tbody>
			{% for post in posts %}
			<tr>
				<td><a href="{% url 'blog:edit' pk=post.id %}">{{ post.titulo }}</a></td>
				<td>{{ post.texto }}</td>
				<td>
					<a class="btn btn-default" href="{% url 'blog:edit' pk=post.id %}" role="button">
						<i class="glyphicon glyphicon-pencil"></i>
					</a>
					<a class="btn btn-default" href="{% url 'blog:remove' pk=post.id %}" role="button">
						<i class="glyphicon glyphicon-trash"></i>
					</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}